# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f515863147373b8ae3eace63323fbbe4de93b86a6a33f57fad03c483abbf76be8f5fe933b0c906b1f7d2558332f69a43b01a816ea85136bb4851a5bcee45e65b

test:
  secret_key_base: 155a14e63d1aa4689511e8a65d7b5a8ac8813221d5e07eb3842cf8394a09473fb9aaac5252a3b5150148bd310834bc2e4014b1c5ae74c9b1b1e41f5242b9f842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
